In [1]:
import cv2
import random
import numpy as np

In [23]:
for person in person_list:
    print(person["height"])

231
272
224
38
23


In [ ]:
img = cv2.imread("asset/Bus_Delhi_1.jpg", 1)
img = cv2.resize(img, (0,0), fx=0.5, fy=0.5)

person_list = []

for index in range(1,6):
    person = {}
    im = cv2.imread(f"asset/Person_{index}.jpg", 0)
    im = cv2.resize(im, (0,0), fx=0.5, fy=0.5)
    h, w = im.shape

    person["image"]  = im
    person["height"] = h
    person["width"]  = w

    person_list.append(person)

methods = [
    cv2.TM_CCOEFF,
    cv2.TM_CCOEFF_NORMED,
]

for method in methods:
    img2 = img.copy()
    img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

    for person in person_list:
        result = cv2.matchTemplate(img2, person["image"], method)
        min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(result)
        
        person["location_1"] = max_loc
        person["location_2"] = (max_loc[0] + person["width"], max_loc[1] + person["height"])
    
        cv2.rectangle(img, person["location_1"], person["location_2"], (255, 255, 255), 3)
    
    cv2.imshow("Match",img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [38]:
print(img)

[[[239 231 205]
  [230 211 242]
  [225 239 218]
  ...
  [234 224 204]
  [248 249 207]
  [250 253 210]]

 [[209 231 209]
  [244 247 251]
  [211 245 239]
  ...
  [221 242 254]
  [232 232 202]
  [218 240 225]]

 [[211 236 232]
  [202 246 223]
  [215 232 245]
  ...
  [243 234 249]
  [249 213 241]
  [231 253 224]]

 ...

 [[207 251 241]
  [213 231 226]
  [214 238 244]
  ...
  [243 216 213]
  [204 242 220]
  [211 230 236]]

 [[213 216 202]
  [212 219 237]
  [211 222 231]
  ...
  [224 217 235]
  [203 245 235]
  [202 246 225]]

 [[247 219 210]
  [221 250 230]
  [238 203 242]
  ...
  [253 203 232]
  [204 202 218]
  [210 243 217]]]


In [7]:
BGR_COLOR = np.array([[[255,0,0],[255,0,0]],[[255,0,0],[255,0,0]]])

print(BGR_COLOR)

cv2.imshow("Image",BGR_COLOR)
cv2.waitKey(0)
cv2.destroyAllWindows()
# x = cv2.cvtColor(BGR_COLOR, cv2.COLOR_BGR2HSV)



cv2.imshow("Image",BGR_COLOR)

[[[255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]]]


error: OpenCV(4.8.0) D:/a/opencv-python/opencv-python/opencv/modules/highgui/src/precomp.hpp:155: error: (-215:Assertion failed) src_depth != CV_16F && src_depth != CV_32S in function 'convertToShow'
